### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'task'

### ISSUE THREAD

**Issue by Splendon** [kienduynguyen/BoxeR#7]
python tools/run.py --config e2edet/config/COCO-Detection/boxer2d_R_50_3x.yaml --model boxer2d --task detection
include path: /nvmelv/cwh8szh/BoxeR/e2edet/config/base_boxer2d_detection.yaml
Traceback (most recent call last):
  File "tools/run.py", line 82, in <module>
    run()
  File "tools/run.py", line 47, in run
    configuration = Configuration(args)
  File "/nvmelv/cwh8szh/BoxeR/e2edet/utils/configuration.py", line 72, in __init__
    self._update_specific(self.config, args)
  File "/nvmelv/cwh8szh/BoxeR/e2edet/utils/configuration.py", line 244, in _update_specific
    config.task = args.task
AttributeError: 'NoneType' object has no attribute 'task'

**Comment by kienduynguyen** [comment]
Hi,

I fixed the configuration problem. Please recheck it!
