### ISSUE TITLE
TypeError: meshgrid() got an unexpected keyword argument 'indexing'

### ISSUE THREAD

**Issue by Splendon** [kienduynguyen/BoxeR#8]
Loaded pretrained resnet: <All keys matched successfully>
Traceback (most recent call last):
  File "tools/run.py", line 82, in <module>
    run()
  File "tools/run.py", line 71, in run
    torch.multiprocessing.spawn(
  File "/root/anaconda3/envs/cwhpy38/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/anaconda3/envs/cwhpy38/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/root/anaconda3/envs/cwhpy38/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/root/anaconda3/envs/cwhpy38/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/nvmelv/cwh8szh/BoxeR/tools/run.py", line 40, in distributed_main
    main(configuration, init_distributed=True)
  File "/nvmelv/cwh8szh/BoxeR/tools/run.py", line 29, in main
    trainer.load()
  File "/nvmelv/cwh8szh/BoxeR/e2edet/trainer/base_trainer.py", line 57, in load
    self.load_model_and_optimizer()
  File "/nvmelv/cwh8szh/BoxeR/e2edet/trainer/base_trainer.py", line 103, in load_model_and_optimizer
    self.model = build_model(self.config, num_classes)
  File "/nvmelv/cwh8szh/BoxeR/e2edet/model/__init__.py", line 22, in build_model
    model.build()
  File "/nvmelv/cwh8szh/BoxeR/e2edet/model/base_model.py", line 46, in build
    self._build()
  File "/nvmelv/cwh8szh/BoxeR/e2edet/model/boxer2d.py", line 54, in _build
    self.transformer = build_transformer(self.config.transformer)
  File "/nvmelv/cwh8szh/BoxeR/e2edet/module/transformer.py", line 392, in build_transformer
    return BoxTransformer(
  File "/nvmelv/cwh8szh/BoxeR/e2edet/module/box_transformer.py", line 33, in __init__
    encoder_layer = BoxTransformerEncoderLayer(
  File "/nvmelv/cwh8szh/BoxeR/e2edet/module/box_transformer.py", line 312, in __init__
    self.self_attn = BoxAttention(d_model, nlevel, nhead)
  File "/nvmelv/cwh8szh/BoxeR/e2edet/module/box_attention.py", line 168, in __init__
    self._create_kernel_indices(kernel_size, "kernel_indices")
  File "/nvmelv/cwh8szh/BoxeR/e2edet/module/box_attention.py", line 182, in _create_kernel_indices
    i, j = torch.meshgrid(indices, indices, indexing="ij")
TypeError: meshgrid() got an unexpected keyword argument 'indexing'

**Comment by Splendon** [comment]
Thanks for solving the this problem

**Comment by kienduynguyen** [comment]
Hi,

This means you are using the old pytorch version. In this codebase, we recommend to use pytorch >= 1.10
